-- 1. Enhance students table with JSONB profiles
ALTER TABLE public.students 
ADD COLUMN IF NOT EXISTS medical_profile JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS logistics_profile JSONB DEFAULT '{}'::jsonb;

-- 2. Create student_documents table
CREATE TABLE IF NOT EXISTS public.student_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id UUID REFERENCES public.students(id) NOT NULL,
    document_type TEXT NOT NULL, -- 'passport', 'visa_usa', 'birth_certificate', 'medical_proof', 'service_contract', 'code_of_conduct', 'other'
    file_path TEXT NOT NULL,
    document_number TEXT,
    expiration_date DATE,
    status TEXT CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for student_documents
ALTER TABLE public.student_documents ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users (staff) to manage all documents
CREATE POLICY "Staff can manage all documents" 
ON public.student_documents 
FOR ALL 
USING (auth.role() = 'authenticated');

-- 3. Create magic_links table
CREATE TABLE IF NOT EXISTS public.magic_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id UUID REFERENCES public.students(id) NOT NULL,
    token TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for magic_links
ALTER TABLE public.magic_links ENABLE ROW LEVEL SECURITY;

-- Staff can generate and view links
CREATE POLICY "Staff can manage magic links" 
ON public.magic_links 
FOR ALL 
USING (auth.role() = 'authenticated');

-- Public access to read magic links (needed to validate token)
-- We only allow reading if you know the exact token (handled by application logic / edge function usually, 
-- but for direct query we might need a function or refined policy. 
-- For now, we will allow SELECT using a security definer function or keep it restricted to authenticated 
-- and use a service role key in the API for validation to be safe, 
-- OR allow anyone to read if they have the token ID. 
-- Let's stick to: Application (API) uses Service Role to validate token. 
-- So no public policy needed here for safety.)

-- 4. Storage Bucket Setup (Attempt to create via SQL)
-- Note: This usually requires the 'storage' extension and schema access.
INSERT INTO storage.buckets (id, name, public)
VALUES ('student-secure-docs', 'student-secure-docs', false)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies for 'student-secure-docs'
-- Allow authenticated staff to do everything
CREATE POLICY "Staff can manage secure docs"
ON storage.objects
FOR ALL
USING ( bucket_id = 'student-secure-docs' AND auth.role() = 'authenticated' );

-- Note: Students accessing via Magic Link will need a signed URL generated by the server,
-- so they don't need direct RLS permissions on the bucket if we use signed URLs for upload/view.
